# Generated by Django 4.0.5 on 2022-06-22 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_budgetmonth_alter_budgetentry_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetentry',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=16),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'date'], name='transaction_category_date'),
        ),
    ]
