# Generated by Django 4.0.5 on 2022-06-28 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_budgetentry_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetentry',
            name='allocated',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='budgetentry',
            name='balance',
            field=models.FloatField(default=0, editable=False),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.FloatField(),
        ),
    ]
