# Generated by Django 4.0.4 on 2022-06-02 03:38

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('transfers', django.db.models.manager.Manager()),
            ],
        ),
    ]
