# Generated by Django 4.0.4 on 2022-06-02 03:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_transaction_managers'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
            ],
        ),
    ]
