# Generated by Django 4.0.4 on 2022-06-03 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_transaction_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='payee',
            name='is_account',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
